logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:4000/kowit
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: create
      use-new-id-generator-mappings: false # hibernate_sequence false
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        hibernate.default_batch_fetch_size: 100
    use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://kowit-prod-kor.cdtoh9nnhedm.eu-west-3.rds.amazonaws.com/kowit
    username: admin
    password: testpassword
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: create
      use-new-id-generator-mappings: false # hibernate_sequence false
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        hibernate.default_batch_fetch_size: 100
    use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

---